### ISSUE TITLE
Failed sink run does not trigger failure POST

### ISSUE THREAD

**Issue by brettgriffin** [fleet-data/fleet#10]
Source task completes, sink tasks fails, yet sink task is never updated. No logs indicate an attempt to update the Sink TaskRun.

```
java.sql.SQLException: [Amazon](500150) Error setting/closing connection: UnknownHostException.
	at com.amazon.redshift.client.PGClient.connect(PGClient.java:559)
	at com.amazon.redshift.client.PGClient.<init>(PGClient.java:350)
	at com.amazon.redshift.core.PGJDBCConnection.connect(PGJDBCConnection.java:583)
	at com.amazon.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
	at com.amazon.jdbc.common.AbstractDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.f8k.jdbc.util.connection.JdbcConnectionProvider.newConnection(JdbcConnectionProvider.java:103)
	at io.f8k.jdbc.util.connection.JdbcConnectionProvider.get(JdbcConnectionProvider.java:36)
	at io.f8k.jdbc.util.connection.JdbcConnectionManager.get(JdbcConnectionManager.java:12)
	at io.f8k.fleet.sink.redshift.helper.SchemaHelper.doesSinkExist(SchemaHelper.java:123)
	at io.f8k.fleet.sink.redshift.helper.SchemaHelper.getSink(SchemaHelper.java:48)
	at io.f8k.fleet.sink.redshift.RedshiftSink.setProperties(RedshiftSink.java:109)
	at io.f8k.fleet.sink.redshift.RedshiftSink.<init>(RedshiftSink.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.fleet.TaskSinkMapping.get(TaskSinkMapping.java:40)
	at io.fleet.Runner.runSink(Runner.java:135)
	at io.fleet.Runner.start(Runner.java:75)
Caused by: com.amazon.support.exceptions.GeneralException: [Amazon](500150) Error setting/closing connection: UnknownHostException.
	... 21 more
Caused by: java.net.UnknownHostException
	at sun.nio.ch.Net.translateException(Net.java:155)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:127)
	at com.amazon.redshift.client.PGClient.connect(PGClient.java:525)
	at com.amazon.redshift.client.PGClient.<init>(PGClient.java:350)
	at com.amazon.redshift.core.PGJDBCConnection.connect(PGJDBCConnection.java:583)
	at com.amazon.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
	at com.amazon.jdbc.common.AbstractDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.f8k.jdbc.util.connection.JdbcConnectionProvider.newConnection(JdbcConnectionProvider.java:103)
	at io.f8k.jdbc.util.connection.JdbcConnectionProvider.get(JdbcConnectionProvider.java:36)
	at io.f8k.jdbc.util.connection.JdbcConnectionManager.get(JdbcConnectionManager.java:12)
	at io.f8k.fleet.sink.redshift.helper.SchemaHelper.doesSinkExist(SchemaHelper.java:123)
	at io.f8k.fleet.sink.redshift.helper.SchemaHelper.getSink(SchemaHelper.java:48)
	at io.f8k.fleet.sink.redshift.RedshiftSink.setProperties(RedshiftSink.java:109)
	at io.f8k.fleet.sink.redshift.RedshiftSink.<init>(RedshiftSink.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.fleet.TaskSinkMapping.get(TaskSinkMapping.java:40)
	at io.fleet.Runner.runSink(Runner.java:135)
	at io.fleet.Runner.start(Runner.java:75)
	at io.fleet.Runner.main(Runner.java:30)
[Amazon](500150) Error setting/closing connection: UnknownHostException.
Exception in OdbcConnectionProvider. Retrying connection initialize one more time
Creating new ODBC connection
[Amazon](500150) Error setting/closing connection: UnknownHostException.
java.sql.SQLException: [Amazon](500150) Error setting/closing connection: UnknownHostException.
	at com.amazon.redshift.client.PGClient.connect(PGClient.java:559)
	at com.amazon.redshift.client.PGClient.<init>(PGClient.java:350)
	at com.amazon.redshift.core.PGJDBCConnection.connect(PGJDBCConnection.java:583)
	at com.amazon.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
	at com.amazon.jdbc.common.AbstractDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.f8k.jdbc.util.connection.JdbcConnectionProvider.newConnection(JdbcConnectionProvider.java:103)
	at io.f8k.jdbc.util.connection.JdbcConnectionProvider.getRetry(JdbcConnectionProvider.java:58)
	at io.f8k.jdbc.util.connection.JdbcConnectionProvider.get(JdbcConnectionProvider.java:46)
	at io.f8k.jdbc.util.connection.JdbcConnectionManager.get(JdbcConnectionManager.java:12)
	at io.f8k.fleet.sink.redshift.helper.SchemaHelper.doesSinkExist(SchemaHelper.java:123)
	at io.f8k.fleet.sink.redshift.helper.SchemaHelper.getSink(SchemaHelper.java:48)
	at io.f8k.fleet.sink.redshift.RedshiftSink.setProperties(RedshiftSink.java:109)
	at io.f8k.fleet.sink.redshift.RedshiftSink.<init>(RedshiftSink.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.fleet.TaskSinkMapping.get(TaskSinkMapping.java:40)
	at io.fleet.Runner.runSink(Runner.java:135)
	at io.fleet.Runner.start(Runner.java:75)
Caused by: com.amazon.support.exceptions.GeneralException: [Amazon](500150) Error setting/closing connection: UnknownHostException.
	... 22 more
Caused by: java.net.UnknownHostException
	at sun.nio.ch.Net.translateException(Net.java:155)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:127)
	at com.amazon.redshift.client.PGClient.connect(PGClient.java:525)
	at com.amazon.redshift.client.PGClient.<init>(PGClient.java:350)
	at com.amazon.redshift.core.PGJDBCConnection.connect(PGJDBCConnection.java:583)
	at com.amazon.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
	at com.amazon.jdbc.common.AbstractDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.f8k.jdbc.util.connection.JdbcConnectionProvider.newConnection(JdbcConnectionProvider.java:103)
	at io.f8k.jdbc.util.connection.JdbcConnectionProvider.getRetry(JdbcConnectionProvider.java:58)
	at io.f8k.jdbc.util.connection.JdbcConnectionProvider.get(JdbcConnectionProvider.java:46)
	at io.f8k.jdbc.util.connection.JdbcConnectionManager.get(JdbcConnectionManager.java:12)
	at io.f8k.fleet.sink.redshift.helper.SchemaHelper.doesSinkExist(SchemaHelper.java:123)
	at io.f8k.fleet.sink.redshift.helper.SchemaHelper.getSink(SchemaHelper.java:48)
	at io.f8k.fleet.sink.redshift.RedshiftSink.setProperties(RedshiftSink.java:109)
	at io.f8k.fleet.sink.redshift.RedshiftSink.<init>(RedshiftSink.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.fleet.TaskSinkMapping.get(TaskSinkMapping.java:40)
	at io.fleet.Runner.runSink(Runner.java:135)
	at io.fleet.Runner.start(Runner.java:75)
	at io.fleet.Runner.main(Runner.java:30)
Exception in OdbcConnectionProvider after retrying connection initialize
null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.fleet.TaskSinkMapping.get(TaskSinkMapping.java:40)
	at io.fleet.Runner.runSink(Runner.java:135)
	at io.fleet.Runner.start(Runner.java:75)
	at io.fleet.Runner.main(Runner.java:30)
Caused by: java.sql.SQLException: [Amazon](500150) Error setting/closing connection: UnknownHostException.
	at com.amazon.redshift.client.PGClient.connect(PGClient.java:559)
	at com.amazon.redshift.client.PGClient.<init>(PGClient.java:350)
	at com.amazon.redshift.core.PGJDBCConnection.connect(PGJDBCConnection.java:583)
	at com.amazon.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
	at com.amazon.jdbc.common.AbstractDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.f8k.jdbc.util.connection.JdbcConnectionProvider.newConnection(JdbcConnectionProvider.java:103)
	at io.f8k.jdbc.util.connection.JdbcConnectionProvider.getRetry(JdbcConnectionProvider.java:58)
	at io.f8k.jdbc.util.connection.JdbcConnectionProvider.get(JdbcConnectionProvider.java:46)
	at io.f8k.jdbc.util.connection.JdbcConnectionManager.get(JdbcConnectionManager.java:12)
	at io.f8k.fleet.sink.redshift.helper.SchemaHelper.doesSinkExist(SchemaHelper.java:123)
	at io.f8k.fleet.sink.redshift.helper.SchemaHelper.getSink(SchemaHelper.java:48)
	at io.f8k.fleet.sink.redshift.RedshiftSink.setProperties(RedshiftSink.java:109)
	at io.f8k.fleet.sink.redshift.RedshiftSink.<init>(RedshiftSink.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.fleet.TaskSinkMapping.get(TaskSinkMapping.java:40)
	at io.fleet.Runner.runSink(Runner.java:135)
	at io.fleet.Runner.start(Runner.java:75)
Caused by: com.amazon.support.exceptions.GeneralException: [Amazon](500150) Error setting/closing connection: UnknownHostException.
	... 22 more
Caused by: java.net.UnknownHostException
	at sun.nio.ch.Net.translateException(Net.java:155)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:127)
	at com.amazon.redshift.client.PGClient.connect(PGClient.java:525)
	at com.amazon.redshift.client.PGClient.<init>(PGClient.java:350)
	at com.amazon.redshift.core.PGJDBCConnection.connect(PGJDBCConnection.java:583)
	at com.amazon.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
	at com.amazon.jdbc.common.AbstractDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.f8k.jdbc.util.connection.JdbcConnectionProvider.newConnection(JdbcConnectionProvider.java:103)
	at io.f8k.jdbc.util.connection.JdbcConnectionProvider.getRetry(JdbcConnectionProvider.java:58)
	at io.f8k.jdbc.util.connection.JdbcConnectionProvider.get(JdbcConnectionProvider.java:46)
	at io.f8k.jdbc.util.connection.JdbcConnectionManager.get(JdbcConnectionManager.java:12)
	at io.f8k.fleet.sink.redshift.helper.SchemaHelper.doesSinkExist(SchemaHelper.java:123)
	at io.f8k.fleet.sink.redshift.helper.SchemaHelper.getSink(SchemaHelper.java:48)
	at io.f8k.fleet.sink.redshift.RedshiftSink.setProperties(RedshiftSink.java:109)
	at io.f8k.fleet.sink.redshift.RedshiftSink.<init>(RedshiftSink.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.fleet.TaskSinkMapping.get(TaskSinkMapping.java:40)
	at io.fleet.Runner.runSink(Runner.java:135)
	at io.fleet.Runner.start(Runner.java:75)
	at io.fleet.Runner.main(Runner.java:30)
{"success":false,"errors":[null]}

```

**Comment by jre247** [comment]
Fleet 0.0.71 has a fix for this issue.
